In [1]:
import tensorflow as tf

F:\Anaconda\lib\site-packages\h5py\__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
hello = tf.constant('Hello,Tensorflow')
sess = tf.Session()
print(sess.run(hello))

b'Hello,Tensorflow'


In [3]:
# 定义计算(在计算图中)
# 声明常量
a = tf.constant([1,2],name='a')
b = tf.constant([2,3],name='b')
result = a+ b
print(result)

Tensor("add:0", shape=(2,), dtype=int32)


In [4]:
# 执行计算(在会话中)
sess = tf.Session()
print(sess.run(result))

[3 5]


In [5]:
import numpy as np

In [6]:
x_data = np.float32(np.random.rand(2,100))
y_data = np.float32(np.dot([0.1,0.2],x_data)+0.3)

In [7]:
w = tf.Variable(tf.zeros([1,2]))
bias = tf.Variable(tf.zeros([1]))

# 构建线性方程
y = tf.matmul(w,x_data)+bias
# print(y_data)
print(y)

Tensor("add_1:0", shape=(1, 100), dtype=float32)


In [8]:
# sess = tf.Session()
# print(sess.run(y))
loss = tf.reduce_mean(tf.square(y - y_data))
optimizer = tf.train.GradientDescentOptimizer(0.5)
train = optimizer.minimize(loss)

init = tf.global_variables_initializer()

In [9]:
sess = tf.Session()
sess.run(init)  # 初始化
sess.run(train)

In [10]:
for i in range(100):
    w1,b1 = sess.run([w,bias])
    print(w1,b1)
    sess.run(train)     # 模型训练
sess.close()
# pre_y = sess.run(y)
# sess.close()
# print(pre_y)

[[0.2154127  0.22072248]] [0.43894508]
[[0.11030085 0.12430111]] [0.23684813]
[[0.15344074 0.17368758]] [0.33024293]
[[0.12867618 0.15548158]] [0.2873716]
[[0.13562323 0.16809365]] [0.30728847]
[[0.12832302 0.16618049]] [0.29822904]
[[0.1279327  0.17067048]] [0.3025023]
[[0.12467001 0.17193745]] [0.30060607]
[[0.12301881 0.17443983]] [0.30153412]
[[0.12088809 0.17614119]] [0.30114266]
[[0.11921998 0.17799789]] [0.3013444]
[[0.11756006 0.17958522]] [0.30125955]
[[0.11609941 0.18111393]] [0.30129552]
[[0.11473307 0.18250069]] [0.30126613]
[[0.11349394 0.18379666]] [0.30125865]
[[0.11235265 0.18499006]] [0.30123413]
[[0.11130972 0.1860972 ]] [0.30121166]
[[0.11035297 0.18712063]] [0.30118346]
[[0.10947704 0.18806846]] [0.301154]
[[0.10867435 0.18894555]] [0.30112198]
[[0.10793919 0.18975759]] [0.30108872]
[[0.10726575 0.19050927]] [0.3010542]
[[0.10664895 0.19120523]] [0.30101898]
[[0.10608403 0.1918496 ]] [0.30098322]
[[0.10556667 0.19244628]] [0.30094728]
[[0.10509289 0.19299878]] [0.30